# Generated by Django 4.2.3 on 2023-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0005_curso_horas_optat'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='obrigatoria',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
