# Generated by Django 4.2.3 on 2023-10-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0006_disciplina_obrigatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='horas_optat',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
