# Generated by Django 4.2.3 on 2023-10-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0007_alter_curso_horas_optat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='ementa',
        ),
    ]
