# Generated by Django 4.2.5 on 2023-09-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_user_is_active'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.aluno')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.oferta')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
            },
        ),
    ]
