# Generated by Django 4.2.3 on 2023-10-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0004_delete_oferta'),
        ('grade', '0002_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='aprovado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenacao.disciplina'),
        ),
    ]
