# Generated by Django 4.2.3 on 2023-08-16 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0002_remove_curso_created_by'),
        ('autenticacao', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordenacao.curso'),
        ),
    ]
