# Generated by Django 4.2.5 on 2023-09-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0004_delete_oferta'),
        ('autenticacao', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordenacao.curso'),
        ),
    ]
