# Generated by Django 4.2.3 on 2023-10-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenacao', '0004_delete_oferta'),
        ('autenticacao', '0005_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordenacao.curso'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coordenacao.curso'),
        ),
    ]
